[project]
name = "employee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beeai-framework>=0.1.4",
    "mcp[cli]>=1.3.0",
    "clickhouse-connect>=0.7.2",
    "pandas>=2.0.0",
    "numpy>=1.20.0"
]
